name: challenge_tag
description: "A tag widget for 100Days100Apps challenge"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Russo
      fonts:
        - asset: fonts/RussoOne-Regular.ttf